import { T } from './tokens.js';

// The shared style object. Every entry is built from the design tokens in
// tokens.js: no raw hex codes or magic numbers live here.
export const S = {
  root: {
    fontFamily: T.font.system,
    color: T.color.textPrimary,
    padding: T.space.padRoot,
  },
  sectionTitle: {
    fontSize: T.fontSize.md,
    fontWeight: T.fontWeight.semibold,
    color: T.color.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: T.space.base,
    marginTop: T.space.section,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: T.space.base,
    marginBottom: T.space.lg,
  },
  statCard: {
    padding: T.space.padStatCard,
    background: T.color.surface,
    border: `1px solid ${T.color.border}`,
    borderRadius: T.radius.lg,
  },
  statLabel: {
    fontSize: T.fontSize.xs,
    color: T.color.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  statValue: {
    fontSize: T.fontSize.lg,
    fontWeight: T.fontWeight.bold,
    color: T.color.textPrimary,
    marginTop: T.space.xs,
  },
  statSub: { fontSize: T.fontSize.xs, color: T.color.textMuted, marginTop: T.space.xxs },
  dot: (color) => ({
    display: 'inline-block',
    width: 8,
    height: 8,
    borderRadius: T.radius.full,
    background: color,
    marginRight: T.space.sm,
    verticalAlign: 'middle',
  }),
  btn: {
    padding: T.space.padBtn,
    border: 'none',
    borderRadius: T.radius.sm,
    fontSize: T.fontSize.sm,
    fontWeight: T.fontWeight.semibold,
    background: T.color.primary,
    color: T.color.white,
    cursor: 'pointer',
  },
  btnSecondary: {
    background: T.color.surfaceSubtle,
    color: T.color.secondaryText,
    border: `1px solid ${T.color.secondaryBorder}`,
  },
  btnSave: { padding: T.space.padBtnSave, fontSize: T.fontSize.md },
  btnDisabled: { opacity: 0.5, cursor: 'not-allowed' },
  inlineRow: {
    display: 'flex',
    alignItems: 'center',
    gap: T.space.lg,
    marginTop: T.space.sm,
    flexWrap: 'wrap',
  },
  fieldRow: {
    display: 'flex',
    alignItems: 'center',
    gap: T.space.lg,
    marginBottom: T.space.base,
    flexWrap: 'wrap',
  },
  fieldLabel: {
    fontSize: T.fontSize.md,
    fontWeight: T.fontWeight.medium,
    color: T.color.textSecondary,
    width: 160,
    flexShrink: 0,
  },
  input: {
    padding: T.space.padInput,
    borderRadius: T.radius.sm,
    border: `1px solid ${T.color.borderStrong}`,
    fontSize: T.fontSize.md,
    background: T.color.white,
    color: T.color.textPrimary,
    minWidth: 220,
  },
  inputSmall: { minWidth: 80, width: 100 },
  select: {
    padding: T.space.padSelect,
    borderRadius: T.radius.sm,
    border: `1px solid ${T.color.borderStrong}`,
    fontSize: T.fontSize.sm,
    background: T.color.white,
    color: T.color.textPrimary,
  },
  selectLabel: { fontSize: T.fontSize.xs, color: T.color.textMuted },
  hint: { fontSize: T.fontSize.xs, color: T.color.textMuted },
  testStatus: { fontSize: T.fontSize.sm },
  testOk: { color: T.color.success },
  testErr: { color: T.color.danger },
  pre: {
    background: T.color.surface,
    border: `1px solid ${T.color.border}`,
    borderRadius: T.radius.md,
    padding: T.space.lg,
    fontSize: T.fontSize.xs,
    lineHeight: 1.4,
    overflow: 'auto',
    maxHeight: 280,
    color: T.color.textSecondary,
  },
  empty: { fontSize: T.fontSize.md, color: T.color.textMuted, padding: T.space.padEmpty },
  analyzerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: T.space.base,
    padding: T.space.padAnalyzerRow,
    background: T.color.surface,
    border: `1px solid ${T.color.border}`,
    borderRadius: T.radius.md,
    marginBottom: T.space.sm,
    fontSize: T.fontSize.md,
  },
  analyzerTitle: { flex: 1, fontWeight: T.fontWeight.medium },
  analyzerState: {
    fontSize: T.fontSize.xs,
    color: T.color.textMuted,
    minWidth: 60,
    textAlign: 'right',
  },
  drawer: {
    background: T.color.white,
    border: `1px solid ${T.color.border}`,
    borderRadius: T.radius.md,
    marginTop: -T.space.xxs,
    marginBottom: T.space.md,
    padding: T.space.lg,
  },
  reportEntry: {
    padding: T.space.padReportEntry,
    borderBottom: `1px solid ${T.color.surfaceSubtle}`,
  },
  reportTs: { fontSize: T.fontSize.xs, color: T.color.textMuted, fontFamily: T.font.monoBasic },
  reportBody: {
    fontSize: T.fontSize.sm,
    color: T.color.textPrimary,
    marginTop: T.space.xs,
    whiteSpace: 'pre-wrap',
  },
  reportFailure: { fontSize: T.fontSize.sm, color: T.color.danger, marginTop: T.space.xs },
  fireResult: { fontSize: T.fontSize.xs, marginLeft: T.space.xs },
  textarea: {
    width: '100%',
    minHeight: 180,
    padding: T.space.md,
    fontFamily: T.font.mono,
    fontSize: T.fontSize.xs,
    lineHeight: 1.45,
    border: `1px solid ${T.color.borderStrong}`,
    borderRadius: T.radius.sm,
    background: T.color.white,
    color: T.color.textPrimary,
    resize: 'vertical',
    boxSizing: 'border-box',
  },
  saveBar: {
    position: 'sticky',
    bottom: 0,
    background: T.color.white,
    borderTop: `1px solid ${T.color.border}`,
    padding: T.space.padSaveBar,
    marginTop: T.space.section,
    display: 'flex',
    alignItems: 'center',
    gap: T.space.lg,
  },
};

// Spread S.btn first, then any number of overrides (variants or disabled
// state). Falsy overrides are dropped so callers can pass `cond && S.x`.
export function btn(...overrides) {
  return Object.assign({}, S.btn, ...overrides.filter(Boolean));
}
